spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: aptx4869
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  type-aliases-package: cn.practice
  application:
    name: MusicPlayer